[toppers] Start using libfat.a     Use fat from a task in toppers.
the below needs to be implemented by the MMC layer

undefined reference to `disk_ioctl'
undefined reference to `disk_write'
undefined reference to `disk_read'
undefined reference to `disk_status'
undefined reference to `disk_initialize'
undefined reference to `get_fattime'


git-svn-id: https://wikipediardware.googlecode.com/svn/trunk@124 974c56cd-8151-0410-98c4-7bb2f43fa8c1